name: pysupercourieretl
channels:
  - defaults
dependencies:
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openpyxl=3.1.5
  - pandas=2.3.1
  - pyarrow=19.0.0
  - pyinstaller=6.12.0
  - pytest=8.4.1
  - python=3.12.9
  - xlsxwriter=3.2.3